CTRL_jpos_move_to_target:
    motion_type: "move_to_target"
    move_time: 2.0

CTRL_jpos_stay:
    motion_type: "stay"
    move_time: 2.

CTRL_jpos_swing:
    motion_type: "swing"
    move_time: 5.
    amplitude: [ 0, 0.2, -0.3, 0, 0.2, -0.3,
                 0, 0.2, -0.3, 0, 0.2, -0.3 ]

    frequency: [ 0, 1, 1, 0, 1, 1,
                 0, 1, 1, 0, 1, 1 ]

    phase: [ 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0 ]

#target_jpos: [ -0.8, -1.2, 2.4,
               #0.8, -1.2, 2.4,
               #-0.8, -1.2, 2.4,
               #0.8, -1.2, 2.4 ]

target_jpos: [ -0.2, -1.1, 1.8, 
    0.2, -1.0, 1.8, 
    -0.2, -1.0, 1.8, 
    0.2, -1.0, 1.8 ]

Kp: [ 100, 100, 100, 
      100, 100, 100, 
      100, 100, 100, 
      100, 100, 100 ]

Kd: [ 5., 5., 5., 
      5., 5., 5., 
      5., 5., 5., 
      5., 5., 5. ]


