# Initialization

# Mini
body_height: 0.25
CTRL_move_to_target_height:
    max_rf_z: 50
    min_rf_z: 3
    body_lifting_time: 0.7

# Timing Parameters (sec)

stance_time: 10000.

CTRL_stance:

Kp: [ 110, 110, 110, 
      110, 110, 110, 
      110, 110, 110, 
      110, 110, 110 ]

Kd: [ 2.0, 2.0, 2.0, 
      2.0, 2.0, 2.0, 
      2.0, 2.0, 2.0, 
      2.0, 2.0, 2.0 ]

Kp_joint: [5.0, 5.0, 5.0]
Kd_joint: [1., 1., 1.]


save_file: false
#save_file: true
